const $=s=>document.querySelector(s);let state=null,owner='',repo='',token='',sha='',tab='overview';
const api=(path,opts={})=>fetch('https://api.github.com'+path,{...opts,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28',...(opts.headers||{})}});
function b64(s){return btoa(unescape(encodeURIComponent(s)))} function from64(s){return decodeURIComponent(escape(atob(s)))}
async function getFile(){const r=await api(`/repos/${owner}/${repo}/contents/data/site.json?ref=main`);if(!r.ok)throw new Error('Could not read data/site.json. Make sure the repo and token are correct.');const j=await r.json();sha=j.sha;state=JSON.parse(from64(j.content.replace(/\n/g,'')))}
function input(label,path,value,multi=false){return `<div class="field"><label>${label}</label>${multi?`<textarea data-path="${path}">${esc(value)}</textarea>`:`<input data-path="${path}" value="${esc(value)}">`}</div>`}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function val(path){return path.split('.').reduce((a,k)=>a[k],state)}
function setPath(path,v){const parts=path.split('.');let o=state;parts.slice(0,-1).forEach(k=>o=o[k]);o[parts.at(-1)]=v}
function render(){
 $('#pageTitle').textContent=tab[0].toUpperCase()+tab.slice(1);
 const p=$('#panel');
 if(tab==='overview'){p.innerHTML=`<div class="stats"><div class="stat"><div class="eyebrow">Projects</div><b>${state.projects.length}</b></div><div class="stat"><div class="eyebrow">Services</div><b>${state.services.length}</b></div><div class="stat"><div class="eyebrow">Testimonials</div><b>${state.testimonials.length}</b></div><div class="stat"><div class="eyebrow">Status</div><b>Live</b></div></div><div class="card"><h2>Quick start</h2><p class="muted">Edit your content from the sections on the left, then press <b>Save to GitHub</b>. The public site reads its content from data/site.json.</p></div>`}
 if(tab==='site'){p.innerHTML=`<div class="card">${input('Name','site.name',val('site.name'))}${input('Short logo','site.shortName',val('site.shortName'))}${input('Role','site.role',val('site.role'))}${input('Tagline','site.tagline',val('site.tagline'),true)}${input('Email','site.email',val('site.email'))}${input('Location','site.location',val('site.location'))}${input('Availability','site.availability',val('site.availability'))}<h3>Hero</h3>${input('Eyebrow','hero.eyebrow',val('hero.eyebrow'))}${input('Hero title','hero.title',val('hero.title'))}${input('Hero description','hero.description',val('hero.description'),true)}${input('Hero image path','hero.heroImage',val('hero.heroImage'))}</div>`}
 if(tab==='about'){p.innerHTML=`<div class="card">${input('Eyebrow','about.eyebrow',val('about.eyebrow'))}${input('Title','about.title',val('about.title'))}${input('About text','about.text',val('about.text'),true)}<h3>Stats</h3>${state.about.stats.map((s,i)=>`<div class="two">${input('Value',`about.stats.${i}.value`,s.value)}${input('Label',`about.stats.${i}.label`,s.label)}</div>`).join('')}</div>`}
 if(tab==='services'){p.innerHTML=`<div class="card">${state.services.map((s,i)=>`<div class="two">${input('Title',`services.${i}.title`,s.title)}${input('Description',`services.${i}.description`,s.description,true)}</div>`).join('')}</div>`}
 if(tab==='testimonials'){p.innerHTML=`<div class="card">${state.testimonials.map((s,i)=>`<div class="two">${input('Quote',`testimonials.${i}.quote`,s.quote,true)}${input('Name / Role',`testimonials.${i}.name`,s.name)}${input('Role',`testimonials.${i}.role`,s.role)}</div>`).join('')}</div>`}
 if(tab==='theme'){p.innerHTML=`<div class="card"><h2>Visual system</h2><div class="two">${input('Accent color','settings.accent',val('settings.accent'))}${input('Dark color','settings.dark',val('settings.dark'))}</div>${input('Light / paper color','settings.light',val('settings.light'))}${input('Font stack','settings.font',val('settings.font'))}<p class="muted">Use the Advanced JSON editor if you want to add new theme variables or future features.</p></div>`}
if(tab==='advanced'){p.innerHTML=`<div class="card"><p class="muted">This is the master editor. Every public-site setting lives in <code>data/site.json</code>. Edit the JSON directly to change or add any feature, section, project, navigation item, social link, theme value or content field.</p><div class="field"><label>Complete site.json</label><textarea id="jsonEditor" style="min-height:620px;font-family:ui-monospace,SFMono-Regular,monospace;font-size:12px">${esc(JSON.stringify(state,null,2))}</textarea></div><button class="edit" onclick="applyJson()">Apply JSON changes</button></div>`} 
if(tab==='projects'){p.innerHTML=`<div class="card"><p class="muted">Projects are currently edited as structured content. We can expand this screen next with drag-and-drop ordering, image uploads, categories, project pages and rich case-study editing.</p>${state.projects.map((x,i)=>`<div class="project-row"><img class="thumb" src="${esc(x.image)}"><div><h3>${esc(x.title)}</h3><div class="muted">${esc(x.category)} · ${esc(x.year)}</div></div><button class="edit" onclick="editProject(${i})">Edit</button></div>`).join('')}</div>`}
}
function collect(){document.querySelectorAll('[data-path]').forEach(e=>setPath(e.dataset.path,e.value))}
window.applyJson=()=>{try{state=JSON.parse($('#jsonEditor').value);alert('JSON is valid. Press Save to GitHub to publish it.')}catch(e){alert('Invalid JSON: '+e.message)}};
window.editProject=i=>{const x=state.projects[i];$('#panel').innerHTML=`<div class="card">${input('Title',`projects.${i}.title`,x.title)}${input('Category',`projects.${i}.category`,x.category)}${input('Year',`projects.${i}.year`,x.year)}${input('Image path',`projects.${i}.image`,x.image)}${input('Description',`projects.${i}.description`,x.description,true)}${input('Project link',`projects.${i}.link`,x.link)}</div>`}
async function save(){collect();$('#save').textContent='Saving…';const content=JSON.stringify(state,null,2);const r=await api(`/repos/${owner}/${repo}/contents/data/site.json`,{method:'PUT',body:JSON.stringify({message:'Update portfolio content',content:b64(content),sha,branch:'main'})});if(!r.ok){alert('Save failed: '+(await r.text()));$('#save').textContent='Save to GitHub';return}const j=await r.json();sha=j.content.sha;$('#save').textContent='Saved ✓';setTimeout(()=>$('#save').textContent='Save to GitHub',1600)}
$('#connect').onclick=async()=>{owner=$('#owner').value.trim();repo=$('#repo').value.trim();token=$('#token').value.trim();try{await getFile();sessionStorage.setItem('gh_owner',owner);sessionStorage.setItem('gh_repo',repo);sessionStorage.setItem('gh_token',token);$('#login').classList.add('hidden');$('#dashboard').classList.remove('hidden');render()}catch(e){alert(e.message)}};
$('#logout').onclick=()=>{sessionStorage.clear();location.reload()};$('#save').onclick=save;
document.querySelectorAll('aside nav button').forEach(b=>b.onclick=()=>{collect();tab=b.dataset.tab;document.querySelectorAll('aside nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});
(async()=>{owner=sessionStorage.getItem('gh_owner')||'';repo=sessionStorage.getItem('gh_repo')||'';token=sessionStorage.getItem('gh_token')||'';if(owner&&repo&&token){try{await getFile();$('#login').classList.add('hidden');$('#dashboard').classList.remove('hidden');render()}catch(e){sessionStorage.clear()}}if(!$('#login').classList.contains('hidden')){$('#owner').value=owner;$('#repo').value=repo}})();
