const $=s=>document.querySelector(s);
let state=null,owner='',repo='',token='',sha='',tab='overview';
const api=(path,opts={})=>fetch('https://api.github.com'+path,{...opts,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28',...(opts.headers||{})}});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function b64(s){return btoa(unescape(encodeURIComponent(s)))}
function from64(s){return decodeURIComponent(escape(atob(s)))}
function uid(prefix='item'){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`}
function val(path){return path.split('.').reduce((a,k)=>a[k],state)}
function setPath(path,v){const parts=path.split('.');let o=state;parts.slice(0,-1).forEach(k=>o=o[k]);o[parts.at(-1)]=v}
function input(label,path,value,multi=false){return `<div class="field"><label>${label}</label>${multi?`<textarea data-path="${path}">${esc(value)}</textarea>`:`<input data-path="${path}" value="${esc(value)}">`}</div>`}
function checkbox(label,path,value){return `<label class="check"><input type="checkbox" data-path="${path}" ${value?'checked':''}> ${label}</label>`}
function collect(){document.querySelectorAll('[data-path]').forEach(e=>setPath(e.dataset.path,e.type==='checkbox'?e.checked:e.value))}
function notice(msg,good=true){const n=$('#notice');n.textContent=msg;n.className='notice '+(good?'good':'bad');setTimeout(()=>n.classList.add('hidden'),3500)}
async function getFile(){const r=await api(`/repos/${owner}/${repo}/contents/data/site.json?ref=main`);if(!r.ok)throw new Error('Could not read data/site.json. Check the repository, branch and token permissions.');const j=await r.json();sha=j.sha;state=JSON.parse(from64(j.content.replace(/\n/g,'')));normalize()}
function normalize(){state.site ||= {};state.hero ||= {};state.projects ||= [];state.testimonials ||= [];state.about ||= {stats:[]};state.services ||= [];state.socials ||= [];state.navigation ||= [];state.settings ||= {};state.logo ||= {enabled:false,image:''};state.footer ||= {enabled:true,text:'Designed & built with intention.',copyright:'© {year} {name}',showNavigation:true,showSocials:true};state.hero.portraitEnabled = state.hero.portraitEnabled!==false;state.hero.heroImage ||= '';state.logo.enabled=state.logo.enabled===true}
async function uploadFile(file,folder='assets/media'){
  if(!file) return null;
  if(file.size>10*1024*1024) throw new Error('Please keep portfolio images under 10 MB.');
  const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-');
  const path=`${folder}/${Date.now()}-${safe}`;
  const data=await file.arrayBuffer();let bytes='';const arr=new Uint8Array(data);const chunk=0x8000;for(let i=0;i<arr.length;i+=chunk)bytes+=String.fromCharCode(...arr.subarray(i,i+chunk));
  const r=await api(`/repos/${owner}/${repo}/contents/${path}`,{method:'PUT',body:JSON.stringify({message:`Upload ${path}`,content:btoa(bytes),branch:'main'})});
  if(!r.ok)throw new Error('Image upload failed: '+(await r.text()));
  return path;
}
async function deleteFile(path){if(!path||!path.startsWith('assets/media/'))return;const r=await api(`/repos/${owner}/${repo}/contents/${path}?ref=main`);if(!r.ok)return;const j=await r.json();await api(`/repos/${owner}/${repo}/contents/${path}`,{method:'DELETE',body:JSON.stringify({message:`Remove ${path}`,sha:j.sha,branch:'main'})})}
function fileControl(label,path,enabledPath=''){return `<div class="field"><label>${label}</label><div class="upload"><input type="file" accept="image/*" data-upload-path="${path}">${enabledPath?checkbox('Show on website',enabledPath,val(enabledPath)):''}<button class="secondary" type="button" onclick="handleUpload(this)">Upload</button></div><div class="small">Uploading creates a file in <code>assets/media/</code>. Then save the content.</div></div>`}
window.handleUpload=async(btn)=>{const wrap=btn.parentElement;const f=wrap.querySelector('input[type=file]').files[0];const path=wrap.querySelector('input[type=file]').dataset.uploadPath;if(!f)return notice('Choose an image first.',false);btn.disabled=true;btn.textContent='Uploading…';try{const old=val(path);const uploaded=await uploadFile(f);setPath(path,uploaded);if(old)await deleteFile(old);render();notice('Image uploaded. Press Save to GitHub to publish the content.')}catch(e){notice(e.message,false)}finally{btn.disabled=false;btn.textContent='Upload'}};
function render(){
 $('#pageTitle').textContent=({site:'Site & Hero',projects:'Projects',testimonials:'Testimonials',footer:'Footer',about:'About',services:'Services',theme:'Theme',advanced:'Advanced JSON',overview:'Overview'})[tab]||tab;
 const p=$('#panel');
 if(tab==='overview')p.innerHTML=`<div class="stats"><div class="stat"><div class="eyebrow">Projects</div><b>${state.projects.length}</b></div><div class="stat"><div class="eyebrow">Testimonials</div><b>${state.testimonials.length}</b></div><div class="stat"><div class="eyebrow">Hero portrait</div><b>${state.hero.portraitEnabled&&state.hero.heroImage?'On':'Off'}</b></div><div class="stat"><div class="eyebrow">Logo</div><b>${state.logo.enabled&&state.logo.image?'On':'Off'}</b></div></div><div class="card"><h2>Your CMS controls</h2><p class="muted">Use Projects and Testimonials to add or delete entries. Use Site & Hero to upload/remove your portrait and optional 16×16 logo. Footer controls everything shown at the bottom of the public site.</p></div>`;
 if(tab==='site')p.innerHTML=`<div class="card"><h2>Site identity</h2>${input('Name','site.name',val('site.name'))}${input('Short name / fallback logo','site.shortName',val('site.shortName'))}${input('Professional title','site.role',val('site.role'))}${input('Tagline','site.tagline',val('site.tagline'),true)}${input('Email','site.email',val('site.email'))}${input('Location','site.location',val('site.location'))}${input('Availability','site.availability',val('site.availability'))}</div><div class="card"><h2>16 × 16 logo</h2>${state.logo.image?`<div class="preview"><img src="${esc(state.logo.image)}" width="16" height="16" alt="Logo"><span class="muted">Current logo</span></div>`:''}${fileControl('Logo image','logo.image','logo.enabled')}<button class="danger" type="button" onclick="removeLogo()">Delete logo & hide it</button></div><div class="card"><h2>Hero</h2>${input('Eyebrow','hero.eyebrow',val('hero.eyebrow'))}${input('Hero title','hero.title',val('hero.title'))}${input('Hero description','hero.description',val('hero.description'),true)}${input('Primary button','hero.primaryCta',val('hero.primaryCta'))}${input('Secondary button','hero.secondaryCta',val('hero.secondaryCta'))}${state.hero.heroImage?`<div class="preview"><img src="${esc(state.hero.heroImage)}" alt="Hero portrait"><span class="muted">Current hero portrait</span></div>`:''}${fileControl('Hero portrait','hero.heroImage','hero.portraitEnabled')}<button class="danger" type="button" onclick="removeHeroPortrait()">Delete portrait & hide it</button></div>`;
 if(tab==='projects')p.innerHTML=`<div class="card"><div class="addbar"><div><h2>Projects</h2><p class="muted">Add, edit or delete projects without touching code.</p></div><button class="edit" type="button" onclick="addProject()">+ Add Project</button></div>${state.projects.map((x,i)=>projectEditor(x,i)).join('')}</div>`;
 if(tab==='testimonials')p.innerHTML=`<div class="card"><div class="addbar"><div><h2>Testimonials</h2><p class="muted">Add or delete client testimonials from the dashboard.</p></div><button class="edit" type="button" onclick="addTestimonial()">+ Add Testimonial</button></div>${state.testimonials.map((x,i)=>testimonialEditor(x,i)).join('')}</div>`;
 if(tab==='footer')p.innerHTML=`<div class="card"><h2>Footer</h2>${checkbox('Show footer','footer.enabled',val('footer.enabled'))}${input('Footer text','footer.text',val('footer.text'),true)}${input('Copyright template','footer.copyright',val('footer.copyright'))}${checkbox('Show footer navigation','footer.showNavigation',val('footer.showNavigation'))}${checkbox('Show footer social links','footer.showSocials',val('footer.showSocials'))}<p class="muted">Use <code>{year}</code> and <code>{name}</code> in the copyright field. The year and your site name are filled automatically.</p></div><div class="card"><h3>Footer navigation</h3>${state.navigation.map((n,i)=>`<div class="two">${input('Label',`navigation.${i}.label`,n.label)}${input('Link',`navigation.${i}.href`,n.href)}</div>`).join('')}</div><div class="card"><h3>Social links</h3>${state.socials.map((s,i)=>`<div class="two">${input('Platform',`socials.${i}.label`,s.label)}${input('URL',`socials.${i}.url`,s.url)}</div>`).join('')}</div>`;
 if(tab==='about')p.innerHTML=`<div class="card">${input('Eyebrow','about.eyebrow',val('about.eyebrow'))}${input('Title','about.title',val('about.title'))}${input('About text','about.text',val('about.text'),true)}<h3>Stats</h3>${state.about.stats.map((s,i)=>`<div class="two">${input('Value',`about.stats.${i}.value`,s.value)}${input('Label',`about.stats.${i}.label`,s.label)}</div>`).join('')}</div>`;
 if(tab==='services')p.innerHTML=`<div class="card">${state.services.map((s,i)=>`<div class="two">${input('Title',`services.${i}.title`,s.title)}${input('Description',`services.${i}.description`,s.description,true)}</div>`).join('')}</div>`;
 if(tab==='theme')p.innerHTML=`<div class="card"><h2>Visual system</h2><div class="two">${input('Accent color','settings.accent',val('settings.accent'))}${input('Dark color','settings.dark',val('settings.dark'))}</div>${input('Light / paper color','settings.light',val('settings.light'))}${input('Font stack','settings.font',val('settings.font'))}</div>`;
 if(tab==='advanced')p.innerHTML=`<div class="card"><p class="muted">Master editor for future fields. Normal site management should use the visual controls above.</p><div class="field"><label>Complete site.json</label><textarea id="jsonEditor" class="json-editor">${esc(JSON.stringify(state,null,2))}</textarea></div><button class="edit" type="button" onclick="applyJson()">Apply JSON changes</button></div>`;
}
function projectEditor(x,i){return `<div class="project-card"><div class="item-head"><strong>${esc(x.title||'New Project')}</strong><div class="actions"><button class="danger" type="button" onclick="deleteProject(${i})">Delete</button></div></div><div class="two">${input('Title',`projects.${i}.title`,x.title)}${input('Category',`projects.${i}.category`,x.category)}</div><div class="two">${input('Year',`projects.${i}.year`,x.year)}${input('Project link',`projects.${i}.link`,x.link||'#')}</div>${input('Description',`projects.${i}.description`,x.description,true)}${checkbox('Featured project',`projects.${i}.featured`,!!x.featured)}<div class="preview"><img src="${esc(x.image||'')||'assets/project-01.svg'}" alt=""><div><div class="muted">Image</div><div class="upload"><input type="file" accept="image/*" data-upload-path="projects.${i}.image"><button class="secondary" type="button" onclick="handleUpload(this)">Upload image</button></div></div></div></div>`}
function testimonialEditor(x,i){return `<div class="testimonial-card"><div class="item-head"><strong>${esc(x.name||'New Testimonial')}</strong><button class="danger" type="button" onclick="deleteTestimonial(${i})">Delete</button></div>${input('Quote',`testimonials.${i}.quote`,x.quote,true)}<div class="two">${input('Client name',`testimonials.${i}.name`,x.name)}${input('Role / company',`testimonials.${i}.role`,x.role)}</div></div>`}
window.addProject=()=>{collect();state.projects.push({id:uid('project'),title:'New Project',category:'Category',year:String(new Date().getFullYear()),description:'Project description.',image:'assets/project-01.svg',featured:false,link:'#'});render();notice('Project added. Fill it in, then Save to GitHub.')}
window.deleteProject=i=>{if(!confirm(`Delete “${state.projects[i].title||'this project'}”?`))return;collect();state.projects.splice(i,1);render();notice('Project deleted. Press Save to GitHub to publish.')}
window.addTestimonial=()=>{collect();state.testimonials.push({quote:'A great experience working together.',name:'Client Name',role:'Role, Company'});render();notice('Testimonial added. Fill it in, then Save to GitHub.')}
window.deleteTestimonial=i=>{if(!confirm(`Delete testimonial from “${state.testimonials[i].name||'this client'}”?`))return;collect();state.testimonials.splice(i,1);render();notice('Testimonial deleted. Press Save to GitHub to publish.')}
window.removeLogo=async()=>{if(!confirm('Delete the logo and hide it from the site?'))return;collect();const old=state.logo.image;state.logo.image='';state.logo.enabled=false;try{await deleteFile(old)}catch(e){}render();notice('Logo removed. Press Save to GitHub to publish.')}
window.removeHeroPortrait=async()=>{if(!confirm('Delete the hero portrait and hide it from the site?'))return;collect();const old=state.hero.heroImage;state.hero.heroImage='';state.hero.portraitEnabled=false;try{await deleteFile(old)}catch(e){}render();notice('Hero portrait removed. Press Save to GitHub to publish.')}
window.applyJson=()=>{try{state=JSON.parse($('#jsonEditor').value);normalize();render();notice('JSON is valid. Press Save to GitHub to publish.')}catch(e){notice('Invalid JSON: '+e.message,false)}};
async function save(){collect();$('#save').disabled=true;$('#save').textContent='Saving…';try{const content=JSON.stringify(state,null,2);const r=await api(`/repos/${owner}/${repo}/contents/data/site.json`,{method:'PUT',body:JSON.stringify({message:'Update portfolio content',content:b64(content),sha,branch:'main'})});if(!r.ok)throw new Error(await r.text());const j=await r.json();sha=j.content.sha;$('#save').textContent='Saved ✓';notice('Published to GitHub. GitHub Pages may take a short moment to update.')}catch(e){$('#save').textContent='Save to GitHub';notice('Save failed: '+e.message,false)}finally{setTimeout(()=>{$('#save').disabled=false;if($('#save').textContent==='Saved ✓')$('#save').textContent='Save to GitHub'},1800)}}
$('#connect').onclick=async()=>{owner=$('#owner').value.trim();repo=$('#repo').value.trim();token=$('#token').value.trim();if(!owner||!repo||!token)return alert('Enter your GitHub username, repository and token.');try{await getFile();sessionStorage.setItem('gh_owner',owner);sessionStorage.setItem('gh_repo',repo);sessionStorage.setItem('gh_token',token);$('#login').classList.add('hidden');$('#dashboard').classList.remove('hidden');render()}catch(e){alert(e.message)}};
$('#logout').onclick=()=>{sessionStorage.clear();location.reload()};$('#save').onclick=save;
document.querySelectorAll('aside nav button').forEach(b=>b.onclick=()=>{collect();tab=b.dataset.tab;document.querySelectorAll('aside nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});
(async()=>{owner=sessionStorage.getItem('gh_owner')||'';repo=sessionStorage.getItem('gh_repo')||'';token=sessionStorage.getItem('gh_token')||'';if(owner&&repo&&token){try{await getFile();$('#login').classList.add('hidden');$('#dashboard').classList.remove('hidden');render()}catch(e){sessionStorage.clear()}}if(!$('#login').classList.contains('hidden')){$('#owner').value=owner;$('#repo').value=repo}})();
