const FALLBACK='data/site.json';
function propertyMeta(property,content){let el=document.querySelector(`meta[property="${property}"]`);if(!el){el=document.createElement('meta');el.setAttribute('property',property);document.head.appendChild(el)}el.content=content||''}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=(value,fallback='#')=>{const raw=String(value??'').trim();if(!raw)return fallback;try{const u=new URL(raw,location.href);const allowed=['http:','https:','mailto:','tel:'];if(!allowed.includes(u.protocol))return fallback;if(['http:','https:'].includes(u.protocol)&&u.origin===location.origin)return u.pathname+u.search+u.hash;return raw}catch{return fallback}};
const safeImg=(value,fallback='')=>{const raw=String(value??'').trim();if(!raw)return fallback;try{const u=new URL(raw,location.href);if(['http:','https:','data:'].includes(u.protocol)||raw.startsWith('./')||raw.startsWith('../')||raw.startsWith('/'))return raw;return fallback}catch{return fallback}};
async function loadData(){const r=await fetch(FALLBACK,{cache:'no-store'});if(!r.ok)throw new Error('Content unavailable');return r.json()}
function applySettings(d){const s=d.settings||{};document.documentElement.style.setProperty('--accent',s.accent||'#ff4d1f');document.documentElement.style.setProperty('--ink',s.dark||'#0b0c0e');document.documentElement.style.setProperty('--paper',s.light||'#f5f2eb');document.documentElement.style.setProperty('--max',`${Number(s.maxWidth)||1240}px`);document.documentElement.style.setProperty('--radius',`${Number(s.buttonRadius)||999}px`);document.documentElement.style.setProperty('--card-radius',`${Number(s.cardRadius)||15}px`);document.documentElement.style.setProperty('--image-radius',`${Number(s.imageRadius)||0}px`);document.documentElement.style.setProperty('--body-font',s.font||'DM Sans, system-ui, sans-serif');document.documentElement.style.setProperty('--heading-font',s.headingFont||'Space Grotesk, system-ui, sans-serif');document.documentElement.style.setProperty('--image-filter',s.grayscaleImages===false?'none':'grayscale(1)')}
function meta(name,content){let el=document.querySelector(`meta[name="${name}"]`);if(!el){el=document.createElement('meta');el.name=name;document.head.appendChild(el)}el.content=content||''}
function render(d){
 d.site ||= {}; d.hero ||= {}; d.about ||= {};
 window.__portfolioData=d;applySettings(d);const seo=d.seo||{};document.title=seo.title||`${d.site.name} — ${d.site.role}`;meta('description',seo.description||d.site.tagline||'Graphic designer portfolio');propertyMeta('og:title',seo.title||`${d.site.name} — ${d.site.role}`);propertyMeta('og:description',seo.description||d.site.tagline||'Graphic designer portfolio');meta('twitter:card','summary_large_image');meta('twitter:title',seo.title||`${d.site.name} — ${d.site.role}`);meta('twitter:description',seo.description||d.site.tagline||'Graphic designer portfolio');
 let og=document.querySelector('meta[property="og:image"]');if(!og){og=document.createElement('meta');og.setAttribute('property','og:image');document.head.appendChild(og)}og.content=seo.socialImage||'';if(seo.favicon){let fi=document.querySelector('link[rel="icon"]');if(!fi){fi=document.createElement('link');fi.rel='icon';document.head.appendChild(fi)}fi.href=seo.favicon}
 const vis=d.visibility||{};const nav=(d.navigation||[]).map(n=>`<a href="${esc(safeUrl(n.href))}" ${/^https?:/i.test(String(n.href||''))?'target="_blank" rel="noopener noreferrer"':''}>${esc(n.label)}</a>`).join('');
 const work=d.workSection||{}, servicesSection=d.servicesSection||{}, testimonialsSection=d.testimonialsSection||{}, contact=d.contactSection||{}, header=d.header||{};
 const projects=(d.projects||[]).filter(p=>p.featured!==false||vis.showAllProjects!==false).map((p,i)=>{const original=(d.projects||[]).indexOf(p);return `<article class="project reveal" tabindex="0" role="button" data-project-index="${original}"><div class="project-img"><img src="${esc(safeImg(p.image))}" alt="${esc(p.title)}" loading="lazy" decoding="async" onerror="this.style.display='none'"></div><div class="project-title">${esc(p.title)}</div><div class="project-meta"><span>${esc(p.category)}</span><span>${esc(p.year)}</span></div></article>`}).join('');
 const services=(d.services||[]).map((s,i)=>`<div class="service reveal"><div class="service-no">${String(i+1).padStart(2,'0')}</div><div><h3>${esc(s.title)}</h3><p>${esc(s.description)}</p></div></div>`).join('');
 const quotes=(d.testimonials||[]).map(t=>`<article class="quote reveal">${t.photo&&t.photoEnabled!==false?`<img class="quote-photo" src="${esc(safeImg(t.photo))}" alt="${esc(t.name)}" loading="lazy" decoding="async" onerror="this.remove()">`:''}<blockquote>“${esc(t.quote)}”</blockquote><small>${esc(t.name)}${t.role?' · '+esc(t.role):''}</small></article>`).join('');
 const socials=(d.socials||[]).map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)} ↗</a>`).join('');
 const logo=(d.logo?.enabled&&d.logo?.image)?`<img class="logo-image" src="${esc(safeImg(d.logo.image))}" alt="${esc(d.site.name)} logo">`:`<span>${esc(d.site.shortName)}</span>`;
 const heroPortrait=(d.hero?.portraitEnabled!==false&&d.hero?.heroImage)?`<div class="hero-art"><div class="side-index">01 — 05</div><img src="${esc(safeImg(d.hero.heroImage))}" alt="${esc(d.site.name)}" fetchpriority="high" decoding="async" onerror="this.closest('.hero-art')?.remove()"></div>`:'';
 const footerEnabled=d.footer?.enabled!==false, footerCopyright=(d.footer?.copyright||'© {year} {name}').replace('{year}',new Date().getFullYear()).replace('{name}',d.site.name);const viewAllLabel=d.projectSection?.viewAllLabel||'View All Projects',viewAllUrl=d.projectSection?.viewAllUrl||'#work';
 document.querySelector('#app').innerHTML=`<header class="nav"><div class="container nav-inner"><a class="logo" href="#home">${logo}</a><nav class="links">${nav}</nav><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false">☰</button><a class="hire" href="${esc(safeUrl(header.hireUrl,'#contact'))}">${esc(header.hireLabel||'Hire Me')} →</a></div><nav class="mobile-links" aria-hidden="true">${nav}</nav></header>
 <main id="main-content">
 <section class="hero container ${heroPortrait?'':'no-portrait'}" id="home" ${vis.showHero===false?'hidden':''}><div><div class="eyebrow">${esc(d.hero.eyebrow)}</div><h1>${esc(d.hero.title)}</h1><p>${esc(d.hero.description)}</p><div class="actions"><a class="btn primary" href="${esc(safeUrl(d.hero.primaryCtaUrl,'#work'))}">${esc(d.hero.primaryCta)} →</a><a class="btn" href="${esc(safeUrl(d.hero.secondaryCtaUrl,'#contact'))}">${esc(d.hero.secondaryCta)}</a></div></div>${heroPortrait}</section>
 <section class="section container" id="work" ${vis.showProjects===false?'hidden':''}><div class="section-head"><div><div class="eyebrow">${esc(work.eyebrow||'Featured Work')}</div><h2>${esc(work.title||'Selected Projects')}</h2></div>${viewAllUrl?`<a class="small-link" href="${esc(safeUrl(viewAllUrl,'#work'))}" ${/^https?:/i.test(viewAllUrl)?'target="_blank" rel="noopener noreferrer"':''}>${esc(viewAllLabel)} →</a>`:''}</div><div class="grid">${projects||'<p class="muted">Projects coming soon.</p>'}</div></section>
 <section class="section dark" id="about" ${vis.showAbout===false?'hidden':''}><div class="container about"><div><div class="eyebrow muted">${esc(d.about.eyebrow)}</div><h2>${esc(d.about.title)}</h2></div><div><p>${esc(d.about.text)}</p><div class="stats">${(d.about.stats||[]).map(s=>`<div class="stat"><strong>${esc(s.value)}</strong><span>${esc(s.label)}</span></div>`).join('')}</div></div></div></section>
 <section class="section container" id="services" ${vis.showServices===false?'hidden':''}><div class="section-head"><div><div class="eyebrow">${esc(servicesSection.eyebrow||'What I Do')}</div><h2>${esc(servicesSection.title||'Services')}</h2></div></div><div class="services">${services}</div></section>
 <section class="section container" id="testimonials" ${vis.showTestimonials===false?'hidden':''}><div class="section-head"><div><div class="eyebrow">${esc(testimonialsSection.eyebrow||'Kind Words')}</div><h2>${esc(testimonialsSection.title||'Testimonials')}</h2></div></div><div class="quote-grid">${quotes}</div></section>
 <section class="section container" id="contact" ${vis.showContact===false?'hidden':''}><div class="contact"><div><div class="eyebrow">${esc(contact.eyebrow||"Let's Work Together")}</div><h2>${esc(contact.title||'Have a project in mind?')}</h2><p class="contact-copy">${esc(d.site.availability)}<br>${esc(contact.description||"Let's talk about what we can create.")}</p></div><div><div class="contact-list">${d.contactForm?.enabled?`<div class="contact-cta"><a class="btn primary" href="mailto:${esc(d.site.email)}?subject=${encodeURIComponent(d.contactForm.emailSubject||'New project enquiry')}">${esc(d.contactForm.buttonLabel||'Start a Project')} →</a></div>`:''}<div class="contact-row"><span>Email</span><a href="mailto:${esc(d.site.email)}">${esc(d.site.email)} ↗</a></div><div class="contact-row"><span>Location</span><span>${esc(d.site.location)}</span></div>${socials?`<div class="contact-row"><span>Social</span><span class="social-inline">${socials}</span></div>`:''}</div></div></div></section>
 </main>${footerEnabled?`<footer class="container footer"><div><span>${esc(footerCopyright)}</span>${d.footer?.text?`<span class="footer-text">${esc(d.footer.text)}</span>`:''}</div>${(d.footer?.showNavigation!==false||d.footer?.showSocials!==false)?`<div class="footer-right">${d.footer?.showNavigation!==false?`<nav>${nav}</nav>`:''}${d.footer?.showSocials!==false&&socials?`<div class="footer-socials">${socials}</div>`:''}</div>`:''}</footer>`:''}
 <div id="projectModal" class="project-modal" aria-hidden="true"><div class="project-modal-backdrop" data-close-project></div><div class="project-modal-panel" role="dialog" aria-modal="true" aria-labelledby="projectModalTitle"><button class="project-modal-close" type="button" aria-label="Close project" data-close-project>×</button><div class="project-modal-top"><div><div class="eyebrow" id="projectModalCategory"></div><h2 id="projectModalTitle"></h2><p id="projectModalDescription"></p></div><div class="modal-actions"><a id="projectModalViewMore" class="btn primary" href="#" target="_blank" rel="noopener noreferrer">View More ↗</a></div></div><div id="projectDetails" class="case-study-details"></div><div id="projectGallery" class="project-gallery"></div><div class="project-nav"><button type="button" id="prevProject">← Previous</button><button type="button" id="nextProject">Next →</button></div></div></div>`;
 const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('show')),{threshold:.08});document.querySelectorAll('.reveal').forEach(x=>obs.observe(x));
 document.querySelectorAll('[data-project-index]').forEach(card=>{card.addEventListener('click',()=>openProject(Number(card.dataset.projectIndex)));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openProject(Number(card.dataset.projectIndex))}})});document.querySelectorAll('[data-close-project]').forEach(x=>x.addEventListener('click',closeProject));document.querySelector('#prevProject').addEventListener('click',()=>navigateProject(-1));document.querySelector('#nextProject').addEventListener('click',()=>navigateProject(1));
 const toggle=document.querySelector('.menu-toggle'),mobile=document.querySelector('.mobile-links');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));mobile.classList.toggle('open',!open);mobile.setAttribute('aria-hidden',String(open))});mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{toggle.setAttribute('aria-expanded','false');mobile.classList.remove('open')}));
}
function openProject(index){const d=window.__portfolioData,p=d.projects[index];if(!p)return;window.__projectIndex=index;const gallery=[{image:p.image,title:p.title},...(Array.isArray(p.gallery)?p.gallery:[])].filter(x=>x&&x.image);document.querySelector('#projectModalCategory').textContent=[p.category,p.year,p.client].filter(Boolean).join(' · ');document.querySelector('#projectModalTitle').textContent=p.title||'';document.querySelector('#projectModalDescription').textContent=p.description||'';const more=document.querySelector('#projectModalViewMore');more.textContent=(p.viewMoreLabel||'View More')+' ↗';more.href=safeUrl(p.viewMoreUrl,'#');more.style.display=p.viewMoreUrl?'inline-flex':'none';
 const details=[['Client',p.client],['Role',p.role],['Overview',p.overview],['Challenge',p.challenge],['Strategy',p.strategy],['Solution',p.solution],['Results',p.results]].filter(x=>x[1]);document.querySelector('#projectDetails').innerHTML=details.map(x=>`<div class="case-block"><div class="eyebrow">${esc(x[0])}</div><p>${esc(x[1])}</p></div>`).join('');document.querySelector('#projectGallery').innerHTML=gallery.map((g,i)=>`<figure class="gallery-item ${i===0?'gallery-cover':''}"><img src="${esc(safeImg(g.image))}" alt="${esc(g.title||p.title)}" loading="lazy" decoding="async" onerror="this.closest('figure')?.remove()"><figcaption>${esc(g.title||p.title||`Image ${i+1}`)}</figcaption></figure>`).join('');document.querySelector('#projectModal').classList.add('open');document.querySelector('#projectModal').setAttribute('aria-hidden','false');document.body.classList.add('modal-open');document.querySelector('.project-modal-close').focus()}
function navigateProject(dir){const d=window.__portfolioData;if(!d?.projects?.length)return;let i=window.__projectIndex+dir;if(i<0)i=d.projects.length-1;if(i>=d.projects.length)i=0;openProject(i)}
function closeProject(){const modal=document.querySelector('#projectModal');if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');document.querySelector(`[data-project-index="${window.__projectIndex}"]`)?.focus()}
document.addEventListener('keydown',e=>{const modal=document.querySelector('#projectModal.open');if(e.key==='Escape'&&modal)closeProject();if(modal&&(e.key==='ArrowLeft'||e.key==='ArrowRight'))navigateProject(e.key==='ArrowLeft'?-1:1);if(modal&&e.key==='Tab'){const focusables=[...modal.querySelectorAll('button,a[href],input,textarea,select,[tabindex]:not([tabindex="-1"])')].filter(x=>!x.disabled&&x.offsetParent!==null);if(focusables.length){const first=focusables[0],last=focusables.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}});
loadData().then(render).catch(()=>document.querySelector('#app').innerHTML='<div style="padding:40px;font-family:system-ui">Could not load site content.</div>');
